services:
  - type: web
    name: jobscout-backend
    env: python
    buildCommand: |
      apt-get update && apt-get install -y chromium chromium-chromedriver
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: GOOGLE_CHROME_BIN
        value: /usr/bin/chromium
      - key: CHROMEDRIVER_PATH
        value: /usr/lib/chromium-browser/chromedriver
