services:
  - type: web
    name: jobscout-backend
    env: python
    buildCommand: |
    apt-get update
    apt-get install -y wget unzip
    # Download and install Chromium 137
    wget -O /tmp/chrome-linux.zip https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/137.0.7151.55/linux64/chrome-linux64.zip
    unzip /tmp/chrome-linux.zip -d /tmp/
    mv /tmp/chrome-linux64 /opt/chrome
    ln -s /opt/chrome/chrome /usr/bin/chromium
    # Download and install Chromedriver 137
    wget -O /tmp/chromedriver.zip https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/137.0.7151.55/linux64/chromedriver-linux64.zip
    unzip /tmp/chromedriver.zip -d /tmp/
    mv /tmp/chromedriver-linux64/chromedriver /usr/bin/chromedriver
    chmod +x /usr/bin/chromedriver
    pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_CHROME_BIN
        value: /opt/chrome/chrome
      - key: CHROMEDRIVER_PATH
        value: /usr/bin/chromedriver
      - key: PYTHON_VERSION
        value: 3.12.0
      # - key: GOOGLE_CHROME_BIN
      #   value: /usr/bin/chromium
      # - key: CHROMEDRIVER_PATH
      #   value: /usr/bin/chromedriver
