services:
  - type: web
    name: jobscout-backend
    env: python
    buildCommand: |
    apt-get update
    apt-get install -y chromium wget unzip
    chromium --version
    echo "==== /usr/bin ===="
    ls -l /usr/bin | grep chromedriver || true
    echo "==== /usr/lib ===="
    ls -l /usr/lib | grep chromedriver || true
    echo "==== /usr/lib/chromium-browser ===="
    ls -l /usr/lib/chromium-browser || true
    echo "==== /usr/lib/chromium ===="
    ls -l /usr/lib/chromium || true
    # Download a known chromedriver version (adjust version if needed)
    wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
    unzip /tmp/chromedriver.zip -d /tmp/
    mv /tmp/chromedriver /usr/bin/chromedriver
    chmod +x /usr/bin/chromedriver
    ls -l /usr/bin/chromedriver
    pip install -r requirements.txt
    # buildCommand: |
    # apt-get update
    # apt-get install -y chromium wget unzip
    # # Get Chromium version
    # chromium --version
    # # Download matching chromedriver (for Chromium 122, for example)
    # wget -O /tmp/chromedriver.zip https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.111/linux64/chromedriver-linux64.zip
    # unzip /tmp/chromedriver.zip -d /tmp/
    # mv /tmp/chromedriver-linux64/chromedriver /usr/bin/chromedriver
    # chmod +x /usr/bin/chromedriver
    # pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: GOOGLE_CHROME_BIN
        value: /usr/bin/chromium
      - key: CHROMEDRIVER_PATH
        value: /usr/bin/chromedriver
